import { MenuItem, Review } from './types';

export const RESTAURANT_INFO = {
  name: "L'Ambroisie Bistro",
  tagline: "Fine Modern Dining & Cozy Atmosphere",
  phone: "+1 (555) 432-8900",
  email: "reservations@ambroisiebistro.com",
  address: "482 Culinary Heights Blvd, Gourmet District, NY 10013",
  hours: {
    weekday: "11:30 AM - 10:00 PM",
    weekend: "11:00 AM - 11:30 PM",
    days: "Open Daily",
    lunchHours: "Lunch: 11:30 AM - 3:30 PM",
    dinnerHours: "Dinner: 5:00 PM - Close",
  },
  openingHourNum: 11.5, // 11:30 AM
  closingHourNum: 22.0, // 10:00 PM (on weekdays)
};

export const MENU_ITEMS: MenuItem[] = [
  // --- STARTERS ---
  {
    id: "s1",
    name: "Truffle & Parmesan Pomme Frites",
    description: "Double-cooked russet potatoes tossed with white truffle oil, grated high-grade aged Parmesan, and fresh parsley, served with roasted garlic aioli.",
    price: 14.00,
    category: "starters",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegetarian", "gluten-free"],
    rating: 4.8,
    prepTime: "10 min",
    popular: true,
    calories: 420,
  },
  {
    id: "s2",
    name: "Heirloom Tomato Bruschetta",
    description: "Marinated red and yellow heirloom tomatoes, sweet basil, minced garlic, and extra virgin olive oil, served over grilled artisanal sourdough crust with a light balsamic glaze drizzle.",
    price: 12.50,
    category: "starters",
    image: "https://images.unsplash.com/photo-1572656631137-7935297eff55?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegetarian", "vegan"],
    rating: 4.6,
    prepTime: "8 min",
    popular: false,
    calories: 280,
  },
  {
    id: "s3",
    name: "Crispy Calamari Fritti",
    description: "Lightly dusted tender calamari rings fried crisp, served with charred lemon, pickled banana peppers, and a rich spicy house marinara dipping sauce.",
    price: 16.00,
    category: "starters",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80",
    dietary: ["spicy", "nut-free"],
    rating: 4.7,
    prepTime: "12 min",
    popular: true,
    calories: 390,
  },
  {
    id: "s4",
    name: "Artisanal Cheese & Charcuterie Board",
    description: "A curated selection of local triple-cream brie, aged gouda, prosciutto di Parma, and calabrese salami, accompanied by wild honeycomb, cornichons, and flatbreads.",
    price: 22.00,
    category: "starters",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&auto=format&fit=crop&q=80",
    dietary: ["nut-free"],
    rating: 4.9,
    prepTime: "15 min",
    popular: false,
    calories: 580,
  },

  // --- MAINS ---
  {
    id: "m1",
    name: "Pan-Seared Atlantic Salmon",
    description: "Crisp-skinned Atlantic salmon served over a velvety parsnip purée, sautéed asparagus spears, and finished with an orange-fennel beurre blanc sauce.",
    price: 29.50,
    category: "mains",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&auto=format&fit=crop&q=80",
    dietary: ["gluten-free", "nut-free"],
    rating: 4.9,
    prepTime: "20 min",
    popular: true,
    calories: 620,
  },
  {
    id: "m2",
    name: "Prime Aged Ribeye Steak (12oz)",
    description: "USDA Prime 35-day dry-aged ribeye steak, flame-broiled with rosemary garlic butter, served with creamed spinach and roasted rosemary baby potatoes.",
    price: 44.00,
    category: "mains",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["gluten-free", "nut-free"],
    rating: 4.9,
    prepTime: "25 min",
    popular: true,
    calories: 950,
  },
  {
    id: "m3",
    name: "Wild Mushroom & Truffle Risotto",
    description: "Creamy arborio rice cooked slow with a medley of shiitake, chanterelle, and cremini mushrooms, cream, Parmigiano-Reggiano, and topped with shaved winter truffle.",
    price: 26.00,
    category: "mains",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegetarian", "gluten-free"],
    rating: 4.7,
    prepTime: "18 min",
    popular: false,
    calories: 540,
  },
  {
    id: "m4",
    name: "Fiery Thai Basil Tofu Bowl",
    description: "Crispy pressed tofu wok-tossed with sweet peppers, onions, carrots, and fresh Thai holy basil in a fiery chili garlic sauce, served over steaming jasmine rice.",
    price: 21.00,
    category: "mains",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegan", "vegetarian", "spicy", "gluten-free"],
    rating: 4.5,
    prepTime: "14 min",
    popular: false,
    calories: 460,
  },

  // --- DESSERTS ---
  {
    id: "d1",
    name: "Molten Chocolate Lava Cake",
    description: "Decadent dark chocolate cake with a molten warm fudge core, baked fresh and paired with a scoop of Madagascar vanilla bean gelato and fresh raspberry garnish.",
    price: 11.50,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegetarian", "nut-free"],
    rating: 4.9,
    prepTime: "12 min",
    popular: true,
    calories: 510,
  },
  {
    id: "d2",
    name: "Classic Italian Tiramisu",
    description: "Espresso-soaked ladyfinger cookies layered delicately with whipped sweet mascarpone cream, dark rum essence, and finished with a dense dusting of premium cocoa powder.",
    price: 10.00,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegetarian", "nut-free"],
    rating: 4.8,
    prepTime: "5 min",
    popular: true,
    calories: 410,
  },
  {
    id: "d3",
    name: "Meyer Lemon Raspberry Tart",
    description: "Shortbread crust filled with silky, zesty Meyer lemon curd, topped with fresh raspberries, powdered sugar, and a sprig of fresh mint.",
    price: 10.50,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegetarian", "nut-free"],
    rating: 4.6,
    prepTime: "6 min",
    popular: false,
    calories: 340,
  },

  // --- DRINKS ---
  {
    id: "dr1",
    name: "Sparkling Passionfruit Mojito",
    description: "Fresh lime wheels and mint leaves muddled with pure cane sugar, fresh passionfruit pulp, premium silver rum (optional), topped with sparkling mineral water.",
    price: 8.50,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegan", "vegetarian", "gluten-free"],
    rating: 4.7,
    prepTime: "4 min",
    popular: true,
    calories: 140,
  },
  {
    id: "dr2",
    name: "Iced Hibiscus Rose Herbal Tea",
    description: "An aromatic cold-steeped herbal infusion of wild Egyptian hibiscus petals, sweet organic rosewater, organic honey, served chilled over block ice.",
    price: 6.50,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1497534446932-c925b458314e?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegan", "vegetarian", "gluten-free"],
    rating: 4.5,
    prepTime: "3 min",
    popular: false,
    calories: 60,
  },
  {
    id: "dr3",
    name: "Bourbon Smoked Old Fashioned",
    description: "Premium single-barrel Kentucky Bourbon, Angostura bitters, orange peel zest, sweet cherry, cold smoked under glass with cherrywood chips for a rich, aromatic finish.",
    price: 16.00,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&auto=format&fit=crop&q=80",
    dietary: ["vegan", "vegetarian", "gluten-free"],
    rating: 4.9,
    prepTime: "5 min",
    popular: true,
    calories: 160,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev1",
    author: "Samantha K.",
    rating: 5,
    comment: "The Pan-Seared Salmon was absolutely divine! The parsnip purée was so smooth and flavorful. Beautiful ambiance and lovely staff. Definitely coming back!",
    date: "2026-06-28",
    dishName: "Pan-Seared Atlantic Salmon"
  },
  {
    id: "rev2",
    author: "David M.",
    rating: 5,
    comment: "Simply the best Ribeye Steak in the city. Perfectly flame-grilled to medium-rare just as requested. The smoked old fashioned is a spectacular show too!",
    date: "2026-07-02",
    dishName: "Prime Aged Ribeye Steak (12oz)"
  },
  {
    id: "rev3",
    author: "Elena R.",
    rating: 4,
    comment: "Wonderful vegan options like the Fiery Thai Basil Tofu! It had exactly the right level of heat and spice. Service was a little busy but very polite.",
    date: "2026-07-04",
    dishName: "Fiery Thai Basil Tofu Bowl"
  }
];
